# -*- coding: utf-8 -*-
"""220511 SIN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tDrpzmj7apmRj4YZKWizrC9lSn1Rs8cQ
"""

import numpy as np
import math

def sigmoid(x):
    return (1.0/(1 + math.exp(-x)))

lrate = 0.1
INDIM = 2 # 1.0, x
H1DIM = 19 # 적을 수록 지능 감소
OUTDIM = 1

PTTN_NUM = 7

#사인 함수
#0.0 ~ 1.0    sin 0 = 0, sin 90 = 0.5, sin 180 =1.0 


x = np.array([[1.0, 0.01], #0
              [1.0, 0.17], #30
              [1.0, 0.33], #60
              [1.0, 0.50], #90
              [1.0, 0.67], #120
              [1.0, 0.83], #150 
              [1.0, 0.99]]) #180
#첫번째값은 바이어스텀.

"""
t = np.array([ [1.0, 0.0, 0.0],
               [0.0, 1.0, 0.0],
               [0.0, 0.0, 1.0]
               ])
"""
t = np.array( [0.01, 0.50, 0.87, 1.00, 0.87, 0.50, 0.01] )

w1= np.zeros([H1DIM, INDIM])
for i in range(H1DIM) :
  for j in range(INDIM) :
    w1[i][j] = np.random.rand()

#w2 = np.zeros(H1DIM)
#for i in range(H1DIM):
  #w2[i] = np.random.rand()

w2 = np.zeros([OUTDIM, H1DIM])
for i in range(OUTDIM) :
  for j in range(H1DIM) :
    w2[i][j] = np.random.rand()


y1 = np.zeros(H1DIM)
y2 = np.zeros(OUTDIM)

d1 = np.zeros(H1DIM)
d2 = np.zeros(OUTDIM)

for epoch in range (30000):
  if epoch % 10 == 0:
    print ("epoch : ", epoch)


  for p in range(PTTN_NUM) :

    for i in range(H1DIM) :
      out = 0.0
      for j in range(INDIM):
        out += w1[i][j] * x[p][j]
      y1[i] = sigmoid(out)


    for i in range(OUTDIM):
      out = 0.0
      for j in range(H1DIM):
          out += w2[i][j] * y1[i]
      y2[i] = sigmoid(out)
      
      d2[i] = (t[p] - y2[i])

    for i in range(H1DIM) :
      d1[i] = 0.0
      for j in range(OUTDIM) :
        d1[i] = d2[j] * w2[j][i] # w순서주의 w2[j][i]


    for i in range(OUTDIM) :
      for j in range(H1DIM) :
        w2[i][j] += lrate * d2[i] * (y2[i]*(1 - y2[i])) * y1[j]

        
    for i in range(H1DIM) :
      for j in range(INDIM) :
        w1[i][j] += lrate *d1[i] *(y1[i]*(1-y1[i])) * x[p][j]

    if epoch % 10 == 0:
        print(t[p], y2) # 10  01 2개씩 나눠서 보기